// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_PvgAHQOe9BPNLEgeJDPSAKHhxhTcaU',
    appId: '1:833559769252:ios:0a28dc1a7cc22579b8f631',
    messagingSenderId: '833559769252',
    projectId: 'familymart-47554',
    storageBucket: 'familymart-47554.appspot.com',
    iosClientId: '833559769252-6k5ifmtslap747fh5af7s7rag3v2nadc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN2o6G1xLgqZWTa-51aGkQp_UR_Q90_0s',
    appId: '1:833559769252:web:953dda39f4ae161fb8f631',
    messagingSenderId: '833559769252',
    projectId: 'familymart-47554',
    authDomain: 'familymart-47554.firebaseapp.com',
    storageBucket: 'familymart-47554.appspot.com',
    measurementId: 'G-0816W9WH6J',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2o6G1xLgqZWTa-51aGkQp_UR_Q90_0s',
    appId: '1:833559769252:web:953dda39f4ae161fb8f631',
    messagingSenderId: '833559769252',
    projectId: 'familymart-47554',
    authDomain: 'familymart-47554.firebaseapp.com',
    storageBucket: 'familymart-47554.appspot.com',
    measurementId: 'G-0816W9WH6J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_PvgAHQOe9BPNLEgeJDPSAKHhxhTcaU',
    appId: '1:833559769252:ios:0a28dc1a7cc22579b8f631',
    messagingSenderId: '833559769252',
    projectId: 'familymart-47554',
    storageBucket: 'familymart-47554.appspot.com',
    iosClientId: '833559769252-6k5ifmtslap747fh5af7s7rag3v2nadc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiQKovxAu8BNqoS5Ygbn-o1wOGK88laiw',
    appId: '1:833559769252:android:2561b53059498402b8f631',
    messagingSenderId: '833559769252',
    projectId: 'familymart-47554',
    storageBucket: 'familymart-47554.appspot.com',
  );

}